routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Patients\PatientController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('Dashboard.index');
});


Route::controller(PatientController::class)
    ->prefix('patients')
    ->name('patients.')
    ->group(function () {
        Route::get('/list/all', 'index')->name('index');
        Route::get('/details/{patient}', 'show')->name('show');
        Route::get('/new', 'create')->name('create');
        Route::post('/new', 'store')->name('store');
        Route::get('/edit/{patient}', 'edit')->name('edit');
        Route::post('/edit/{patient}', 'update')->name('update');
        Route::delete('/destroy/{patient}', 'destroy')->name('destroy');
    });

app/Models/Patients/Patient.php
<?php

namespace App\Models\Patients;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Patient extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'pid';

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [
        'pid',
    ];
}

app/Models/Users/User.php
<?php

namespace App\Models\Users;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/Patients/PatientController.php
<?php

namespace App\Http\Controllers\Patients;

use App\Models\Patients\Patient;
use App\Http\Controllers\Controller;
use App\Http\Requests\Patients\StorePatientRequest;
use App\Http\Requests\Patients\UpdatePatientRequest;

class PatientController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('Patients.index', ['patients' => Patient::query()->paginate(10)]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('Patients.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StorePatientRequest $request)
    {
        if ($request->secure()) {
            $patient = Patient::query()->create($request->safe()->all());
            return redirect()
                ->route('patients.show', $patient)
                ->with('success', 'Patient created sucessfully.');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Patient $patient)
    {
        return view('Patients.show', ['patient' => $patient]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Patient $patient)
    {
        return view('Patients.edit', ['patient' => $patient]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdatePatientRequest $request, Patient $patient)
    {
        if ($request->secure()) {
            $patient->update($request->safe()->all());
            return redirect()
                ->route('patients.edit', $patient)
                ->with('success', 'Patient updated sucessfully.');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Patient $patient)
    {
        if ($patient->delete()) {
            return back()->with('success', 'Patient PID ' . $patient->pid . ' removed sucessfully.');
        }
    }
}

resources/views/HL7HealthEMR/Dashboard/index.blade.php
@extends('Layouts.internal')

@section('title', 'Welcome!')

@section('sidebar')
@endsection

@section('content')
@endsection

resources/views/HL7HealthEMR/Layouts/internal.blade.php
@inject('carbon', 'Carbon\Carbon')
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}" class="h-100 w-100" data-theme="{{ config('custom.theme.color') }}">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="application-name" content="{{ config('app.name') }}">
    <meta name="description" content="{{ config('custom.system.description') }}">
    <meta name="keywords" content="{{ config('custom.system.keywords') }}">
    <meta name="author" content="{{ config('custom.system.author') }}">
    <meta name="generator" content="{{ config('custom.system.generator') }}">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">

    <title>@yield('title') | {{ config('app.name') }}</title>

    @vite('resources/js/HL7HealthEMR.js')
</head>

<body>
    <div class="drawer drawer-mobile">
        <input id="hl7HealthEMRMenu" type="checkbox" class="drawer-toggle" />
        <div class="drawer-content flex flex-col items-start justify-start h-full">
            <!-- Navbar -->
            @include('Layouts.parts.navbar')

            <div class="container h-full p-10 mx-auto">
                <!-- Notifications -->
                @include('Layouts.parts.notifications')

                <!-- Page content here -->
                @yield('content')
            </div>

            <!-- Footer -->
            @include('Layouts.parts.footer')
        </div>
        <div class="drawer-side">
            <!-- Sidebar -->
            @include('Layouts.parts.sidebar')
        </div>
    </div>
</body>

</html>

resources/views/HL7HealthEMR/Layouts/parts/footer.blade.php
            <footer class="footer items-center p-4 bg-neutral text-neutral-content text-xs">
                <div class="items-center grid-flow-col">
                    <svg width="18" height="18" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"
                        fill-rule="evenodd" clip-rule="evenodd" class="fill-current">
                        <path
                            d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z">
                        </path>
                    </svg>
                    <p>Copyright &copy; {{ config('custom.copyright.year') }} - All right reserved</p>
                </div>
                <div class="grid-flow-col gap-4 md:place-self-center md:justify-self-end">
                    <a>
                        <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24"
                            class="fill-current">
                            <path
                                d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z">
                            </path>
                        </svg>
                    </a>
                    <a>
                        <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24"
                            class="fill-current">
                            <path
                                d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z">
                            </path>
                        </svg>
                    </a>
                    <a>
                        <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24"
                            class="fill-current">
                            <path
                                d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z">
                            </path>
                        </svg>
                    </a>
                </div>
            </footer>

resources/views/HL7HealthEMR/Layouts/parts/navbar.blade.php
            <div class="w-full navbar bg-base-300">
                <div class="flex-none lg:hidden">
                    <label for="hl7HealthEMRMenu" class="btn btn-square btn-ghost drawer-button">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                            class="inline-block w-6 h-6 stroke-current">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M4 6h16M4 12h16M4 18h16"></path>
                        </svg>
                    </label>
                </div>
                <div class="flex-1 px-1 mx-1">@yield('title')</div>

                <div class="dropdown dropdown-end dropdown-hover">
                    <label tabindex="0" class="btn btn-ghost btn-circle avatar">
                        <div class="w-10 rounded-full">
                            <img
                                src="https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?fit=crop&w=85&q=65" />
                        </div>
                    </label>
                    <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
                        <li>
                            <a class="justify-between">
                                Profile
                                <span class="badge">New</span>
                            </a>
                        </li>
                        <li><a>Settings</a></li>
                        <li><a>Logout</a></li>
                    </ul>
                </div>
            </div>

resources/views/HL7HealthEMR/Layouts/parts/notifications.blade.php
                @if (session('success') || session('info') || $errors->any())
                    <div class="toast toast-top toast-end">
                        @if ($errors->any())
                            <div class="flex flex-wrap alert alert-error shadow-lg gap-0 py-2">
                                <div class="flex w-full">
                                    <div class="flex-none w-5">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                            class="stroke-current flex-shrink-0 h-5 w-5 mt-0" fill="none"
                                            viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                        </svg>
                                    </div>
                                    <div class="flex-none w-24 font-bold text-xs">ERROR!</div>
                                    <div class="grow">&nbsp;</div>
                                    <div class="flex-none w-24 text-xxs text-right justify-end">
                                        {{ $carbon::parse('now')->format('M d, Y H:i') }}
                                    </div>
                                </div>
                                @foreach ($errors->all() as $error)
                                    <div class="w-full text-sm gap-0 pt-1">{{ $error }}</div>
                                @endforeach
                            </div>
                        @endif
                        @if (session('success'))
                            <div class="flex flex-wrap alert alert-success shadow-lg gap-0 py-2">
                                <div class="flex w-full">
                                    <div class="flex-none w-5">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                            class="stroke-current flex-shrink-0 h-5 w-5" fill="none"
                                            viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                        </svg>
                                    </div>
                                    <div class="flex-none w-24 font-bold text-xs">SUCCESS</div>
                                    <div class="grow">&nbsp;</div>
                                    <div class="flex-none w-24 text-xxs text-right justify-end">
                                        {{ $carbon::parse('now')->format('M d, Y H:i') }}
                                    </div>
                                </div>
                                <div class="w-full text-sm gap-0 pt-1">{{ session('success') }}</div>
                            </div>
                        @endif
                        @if (session('info'))
                            <div class="flex flex-wrap alert alert-info shadow-lg gap-0 py-2">
                                <div class="flex w-full">
                                    <div class="flex-none w-5">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                            class="stroke-current flex-shrink-0 w-5 h-5">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                        </svg>
                                    </div>
                                    <div class="flex-none w-24 font-bold text-xs">INFO</div>
                                    <div class="grow">&nbsp;</div>
                                    <div class="flex-none w-24 text-xxs text-right justify-end">
                                        {{ $carbon::parse('now')->format('M d, Y H:i') }}
                                    </div>
                                </div>
                                <div class="w-full text-sm gap-0 pt-1">{{ session('info') }}</div>
                            </div>
                        @endif
                    </div>
                @endif

resources/views/HL7HealthEMR/Layouts/parts/sidebar.blade.php
            <label for="hl7HealthEMRMenu" class="drawer-overlay"></label>
            <ul class="menu p-4 w-40 bg-base-100 text-base-content">
                <!-- Sidebar content here -->
                <li>
                    <a href="{{ config('app.url') }}">Dashboard</a>
                </li>
                <li>
                    <a href="{{ route('patients.index') }}">Patients</a>
                </li>
            </ul>
            @section('sidebar')
            @endsection

resources/views/HL7HealthEMR/Patients/create.blade.php
@extends('Layouts.internal')

@section('title', 'New Patient')

@section('sidebar')
@endsection

@section('content')
    <div class="grid grid-cols-4 gap-4">
        <form method="POST" action="{{ route('patients.store') }}" class="col-span-3">
            @csrf
            <div class="form-control w-full max-w-xs">
                <label class="label">
                    <span class="label-text">External ID</span>
                </label>
                <div class=" input-group">
                    <input type="text" value="{{ old('external_ID') }}" name="external_ID" placeholder="External ID"
                        class="input input-bordered w-full max-w-xs" />
                    <button type="submit" class="btn">Save</button>
                </div>
            </div>
        </form>
        <p class="flex justify-end">
            <a class="button" href="{{ route('patients.index') }}">Back to list</a>
        </p>
    </div>
@endsection

resources/views/HL7HealthEMR/Patients/edit.blade.php
@extends('Layouts.internal')

@section('title', 'Edit Patient Details')

@section('sidebar')
@endsection

@section('content')
    <div class="grid grid-cols-4 gap-4">
        <form method="POST" action="{{ route('patients.update', ['patient' => $patient->pid]) }}" class="col-span-3">
            @csrf
            <div class="form-control w-full max-w-xs">
                <label class="label">
                    <span class="label-text">External ID</span>
                </label>
                <div class=" input-group">
                    <input type="text" value="{{ $patient->external_ID }}" name="external_ID" placeholder="External ID"
                        class="input input-bordered w-full max-w-xs" />
                    <button type="submit" class="btn">Save</button>
                </div>
            </div>
        </form>
        <p class="flex justify-end">
            <a class="button" href="{{ route('patients.index') }}">Back to list</a>
        </p>
    </div>
@endsection

resources/views/HL7HealthEMR/Patients/index.blade.php
@extends('Layouts.internal')

@section('title', "Patient's List")

@section('sidebar')
@endsection

@section('content')
    <table class="table table-zebra w-full">
        <!-- head -->
        <thead>
            <tr class="text-center">
                <th>PID</th>
                <th>EID</th>
                <th>Created</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach ($patients as $patient)
                <tr class="text-center">
                    <td>{{ $patient->pid }}</td>
                    <td>{{ $patient->external_ID }}</td>
                    <td>{{ $patient->created_at->format('M d, Y H:i') }}</td>
                    <td class="flex justify-end">
                        <a class="btn btn-square mr-2" href="{{ route('patients.show', ['patient' => $patient->pid]) }}">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                stroke="currentColor" class="w-4 h-4">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                            </svg>
                        </a>
                        <a class="btn btn-square btn-info mr-2"
                            href="{{ route('patients.edit', ['patient' => $patient->pid]) }}">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                stroke="currentColor" class="w-4 h-4">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
                            </svg>

                        </a>
                        <form method="POST" action="{{ route('patients.destroy', ['patient' => $patient->pid]) }}">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-square btn-error" type="submit">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                    stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                                </svg>

                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
        <tfooter>
            <tr>
                <td colspan="4">{{ $patients->links() }}</td>
            </tr>
        </tfooter>
    </table>
    <br />
    <p class="flex justify-end">
        <a href="{{ route('patients.create') }}" class="btn btn-success">New Patient</a>
    </p>
@endsection

resources/views/HL7HealthEMR/Patients/show.blade.php
@extends('Layouts.internal')

@section('title', 'Patient Detail')

@section('sidebar')
@endsection

@section('content')
    <table class="table table-zebra w-full">
        <!-- head -->
        <thead>
            <tr class="text-center">
                <th>PID</th>
                <th>EID</th>
                <th>Created</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr class="text-center">
                <td>{{ $patient->pid }}</td>
                <td>{{ $patient->external_ID }}</td>
                <td>{{ $patient->created_at->format('M d, Y H:i') }}</td>
                <td class="flex justify-end">
                    <a class="btn btn-square btn-info mr-2" href="{{ route('patients.edit', ['patient' => $patient->pid]) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" class="w-4 h-4">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
                        </svg>

                    </a>
                </td>
            </tr>
        </tbody>
    </table>
    <br />
    <p class="flex justify-end">
        <a href="{{ route('patients.index') }}" class="btn btn-success">Back to list</a>
    </p>
@endsection